### ISSUE TITLE
请教下如何通过 pyocd的rtt进行输入

### ISSUE THREAD

**Issue by Althrone** [XIVN1987/RTTView#2]
XIVN 你好！
我现在使用daplink配合pyocd可以实现单片机到电脑的信息输出，但是直接在命令行输入字符貌似没有输入到芯片内，请问下这个上位机是如何实现的？或者直接明勇pyocd的命令可以实现此效果吗？

**Comment by XIVN1987** [comment]
RTTView.py 中向单片机发送消息的函数是 aDownWrite，这个函数只有十几行，，你可以阅读、理解下

另外你可以在 aDownWrite 中加入针对 aDown.WrOff、aDown.RdOff、aDown.SizeOfBuffer 的 print 打印，，然后执行发送动作，，看看这几个关键参数是否正常。。

**Comment by Althrone** [comment]
感谢回复！因为我没有专门学习过python，只是知道pyocd支持daplink所以来试着用的。
其实我主要想知道的是当时你在测试pyocd rtt功能的时候，是如何测试输入效果的？还是说在命令行使用pyocd的话不支持字符输入的操作？
我原计划是用pyocd结合putty，使用那个telnet功能实现单片机msh的输入输出，就和使用串口输入输出一样。但是就卡在rtt输入这部分。

**Comment by XIVN1987** [comment]
我没用过 pyocd 命令行，，建议查下 pyocd 的文档，或者去 pyocd 社区问下。。
