### ISSUE TITLE
Python运行没有DAPLink选项

### ISSUE THREAD

**Issue by xiaoxinpro** [XIVN1987/RTTView#3]
Python运行没有DAPLink选项

![image](https://github.com/XIVN1987/RTTView/assets/11443745/bb8f0e7f-f695-4ff0-917c-e4f49054692c)

已经安装的pip库：

```
pip install PyQt5
pip install PyQtChart
pip install pyusb
pip install hidapi
pip install pywinusb
pip install pyinstaller
```

没有报错信息，麻烦帮忙看一下。。。

**Comment by XIVN1987** [comment]
1、电脑识别 USB 设备了没有？
2、RTTView 是通过“if (product_name.find("CMSIS-DAP") < 0)”识别 USB 设备是否是 DAPLink 的，，这个 USB 设备的 product_name 中是否有 CMSIS-DAP？
3、可以单步调试看看各个 get_all_connected_interfaces() 函数在哪一步退出的。。

**Comment by xiaoxinpro** [comment]
缺少 `six` 模块，安装后正常。

**Comment by xiaoxinpro** [comment]
建议作者提供一个 `requirements.txt` 文件，方便本地安装。
