### ISSUE TITLE
关于升级了最新的pyocd之后

### ISSUE THREAD

**Issue by qkhhyu** [XIVN1987/RTTView#4]
你好，这边用的合宙的daplink V1能正常使用，但是我用daplink V2就会卡死在打开连接界面
然后我更新了最新的pyocd后，能正常打开界面，但是不能打开连接，请问有尝试过最新的pyocd么

**Comment by XIVN1987** [comment]
我这边测试 daplink v2 使用正常：

![QQ截图20240626090555](https://github.com/XIVN1987/RTTView/assets/7879032/11867167-d250-4f21-8a27-49928881b1ef)

**Comment by qkhhyu** [comment]
啊，看起来像是我这边USB有问题？
![QQ截图20240626093000](https://github.com/XIVN1987/RTTView/assets/46958609/49b77592-6578-4046-98f7-536ed7913227)

**Comment by XIVN1987** [comment]
已更新代码，，你再试下是否可用。。

**Comment by qkhhyu** [comment]
问题已解决，非常感谢大佬

**Comment by qkhhyu** [comment]
大佬你好，我在打包exe文件的时候，这个修改过的pyocd文件夹如何打包进去，正常打包，好像是打包了未修改过的默认的依赖
