### ISSUE TITLE
Not able to read variables from .map file

### ISSUE THREAD

**Issue by giuliosavian** [XIVN1987/RTTView#5]
Hi XIVN1987,

I'm trying to use your application with Jlink, but I'm not able to select and visualize the variables:

![Immagine 2024-10-07 150635](https://github.com/user-attachments/assets/ce8ea165-9e14-4165-a264-b9c94dd51b4c)

I have to define the variables in some section of the code?

**Comment by XIVN1987** [comment]
Please upload your map file.

**Comment by XIVN1987** [comment]
What compiler are you using? Currently, only Keil, IAR, and GCC-generated map files are supported.
