### ISSUE TITLE
大佬怎么添加对RTT控制字符的支持

### ISSUE THREAD

**Issue by ZakiLiu** [XIVN1987/RTTView#7]
如图，怎么添加对RTT控制字符的支持
<img width="848" alt="f50979425d7866c3951ac83ea614343" src="https://github.com/user-attachments/assets/df0bee3c-9f2f-4f32-9b87-929115a2e94e">

**Comment by XIVN1987** [comment]
QTextEdit 不支持 ansi escape sequence 功能，，没法搞，，只能等 QTextEdit 升级支持此功能。。
