### ISSUE TITLE
按 python 打包规范应该提供 pyproject.toml 或 setup.py

### ISSUE THREAD

**Issue by taotieren** [XIVN1987/RTTView#8]
我在 Arch Linux 下进行打包操作

```bash
ERROR Source /build/rttview/src/RTTView-20241127 does not appear to be a Python project: no pyproject.toml or setup.py
```

**Comment by XIVN1987** [comment]
RTTView 是一个 APP，，暂时没有将其制作成 python package 的打算。。

**Comment by taotieren** [comment]
那我用 pyinstaller 打包成一个单独的 linux 可执行文件吧
https://aur.archlinux.org/packages/rttview

**Comment by taotieren** [comment]
![image](https://github.com/user-attachments/assets/e9ff1336-e456-47e1-b392-0f85698a1924)
arch linux 下用 pyinstaller 打包成单文件了
但是这里的动态库过滤 linux 下是 `so` 文件。需要修改做下兼容。

**Comment by XIVN1987** [comment]
已修改，，可以选择 so 动态链接库
